package dfhdl.core
import dfhdl.compiler.ir
import dfhdl.internals.*
import scala.annotation.implicitNotFound

type StepBlock = DFOwner[ir.StepBlock]
object StepBlock:
  def apply(using dfc: DFC): StepBlock =
    val step: ir.StepBlock = ir.StepBlock(
      ir.DFMember.Empty.ref,
      dfc.getMeta,
      dfc.tags
    )
    step.asFE

  // for meta programming only
  private[dfhdl] def forced(using dfc: DFC): StepBlock =
    ir.StepBlock(
      dfc.owner.ref,
      dfc.getMeta,
      dfc.tags
    ).addMember.asFE
end StepBlock

sealed trait Step
object Step extends Step:
  object Ops:
    def ThisStep(using dfc: DFC): Step =
      ir.Goto(
        ir.Goto.ThisStep.refTW[ir.Goto],
        dfc.owner.ref,
        dfc.getMeta,
        dfc.tags
      ).addMember
      Step
    def NextStep(using dfc: DFC): Step =
      ir.Goto(
        ir.Goto.NextStep.refTW[ir.Goto],
        dfc.owner.ref,
        dfc.getMeta,
        dfc.tags
      ).addMember
      Step
    def FirstStep(using dfc: DFC): Step =
      ir.Goto(
        ir.Goto.FirstStep.refTW[ir.Goto],
        dfc.owner.ref,
        dfc.getMeta,
        dfc.tags
      ).addMember
      Step
  end Ops
  // this is called by the compiler plugin to register all steps (for each step block) in the
  def pluginRegisterStep(stepMeta: ir.Meta)(using
      dfc: DFC,
      scope: DFC.Scope.Process
  ): Unit =
    val step = StepBlock(using dfc.setMeta(stepMeta))
    // a unique step key is generated by combining the step's name with its starting line number.
    // This handles cases where step names are reused in different internal scopes, such as within loops or nested steps.
    val stepKey = s"${stepMeta.name}_${stepMeta.position.lineStart}"
    scope.stepCache += (stepKey -> step.asIR)

  // this is called by the compiler plugin and replaces the step's `def`. this will add the
  // step to the context, update its reference to point to the proper owner, and finally run
  // the step's body with the step as its owner.
  def pluginAddStep(stepKey: String)(
      run: => Unit
  )(using dfc: DFC, scope: DFC.Scope.Process): Unit =
    val stepIR = scope.stepCache(stepKey)
    stepIR.addMember
    dfc.mutableDB.newRefFor(stepIR.ownerRef, dfc.owner.asIR)
    dfc.enterOwner(stepIR.asFE)
    run
    dfc.exitOwner()

  // this is called by the compiler plugin and replaces the step's onEntry/onExit/fallThrough `def` with
  // a step block that has the name "onEntry"/"onExit"/"fallThrough" which is special-cases and not treated
  // as a normal step, but just a container for the onEntry/onExit/fallThrough code.
  def pluginOnEntryExitFallThrough(meta: ir.Meta)(
      run: => Any
  )(using dfc: DFC): Unit =
    import dfc.getSet
    val onEntryExitFallThrough = ir.StepBlock(
      dfc.owner.ref,
      meta,
      dfc.tags
    ).addMember
    dfc.enterOwner(onEntryExitFallThrough.asFE)
    val ret = run
    if (onEntryExitFallThrough.isFallThrough)
      Exact.strip(ret) match
        case v: DFValAny =>
          // adding ident placement as the last member of the fall-through block
          DFVal.Alias.AsIs.ident(v)(using dfc.anonymize)
        case _ => // do nothing
    dfc.exitOwner()
  end pluginOnEntryExitFallThrough

  // this is called by the compiler plugin and replaces references (calls) to the step `def`.
  // for the process this is considered as a goto statement.
  def pluginGotoStep(nextStepKey: String)(using dfc: DFC, scope: DFC.Scope.Process): Unit =
    import dfc.getSet
    val nextStep = scope.stepCache(nextStepKey)
    val member: ir.Goto = ir.Goto(
      nextStep.refTW[ir.Goto],
      dfc.owner.ref,
      dfc.getMeta,
      dfc.tags
    )
    member.addMember
end Step
